FIX - Update 17-homework.md
michalsoloducha/git-checker pull request #1
Opened 2021-05-06 14:05 UTC by michalsoloducha

I got a little bit confused at one point and I would change:
"Zrób push z i na gałąź master"
into "Zrób push z lokalnej gałęzi master na znalną"
The initial description is correct but I think the proposed version is easier to understand.

Fixes #74

2021-05-10 20:09 UTC, ziobron requested changes

2021-05-10 20:09 UTC, ziobron commented on 17-homework.md
> +3. Zgodnie z instrukcją dodaj adres zdalnego repozytorium (`git remote add origin ADDRESS`), ale pomiń tworzenie gałęzi main. Zrób push z lokalnej gałęzi master na znalną (`git push -u origin master`
```suggestion
3. Zgodnie z instrukcją dodaj adres zdalnego repozytorium (`git remote add origin ADDRESS`), ale pomiń tworzenie gałęzi main. Zrób push z lokalnej gałęzi master na zdalną (`git push -u origin master`).
```

2021-05-10 20:24 UTC, ziobron commented
Can you please raise this PR against coders-school/git-checker repo with mentioned changes? It's the only way how can I merge it.

2021-05-14 15:45 UTC, michalsoloducha commented
Issue resolved in another PR.

2021-05-14 15:45 UTC, closed without merging