FIX - Update 17-homework.md
michalsoloducha/git-checker pull request #2
Opened 2021-05-06 14:15 UTC by michalsoloducha

After doing some operations in VSC I didn't pass some of the tests. I think it should be clearly stated in the beginning of the homework description that all the commands should be typed in via console.

2021-05-10 20:22 UTC, ziobron requested changes

2021-05-10 20:22 UTC, ziobron commented on 17-homework.md
> +Aha, i użyj proszę komend GIT w konsoli. Dzięki temu automat CI będzie w stanie sprawdzić Tobie zadanie.
```suggestion
Aha, i użyj proszę komend gita i linuxa w konsoli. Dzięki temu automat CI będzie w stanie sprawdzić Twoje zadanie.
```

2021-05-10 20:24 UTC, ziobron commented
Can you please raise this PR against coders-school/git-checker repo with mentioned changes? It's the only way how can I merge it.

2021-05-14 15:44 UTC, closed without merging

2021-05-14 15:45 UTC, michalsoloducha commented
Issue resolved in another PR.